CREATE TABLE `webdb`.`society` (
    `postid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `name` VARCHAR(50) NOT NULL ,
    `verifycode` SMALLINT UNSIGNED NULL DEFAULT NULL ,
    `generalsec` VARCHAR(50) NULL DEFAULT NULL ,
    `username` VARCHAR(50) NOT NULL ,
    `password` TEXT NOT NULL ,
    `email` VARCHAR(40) NULL DEFAULT NULL ,
    `phone` INT UNSIGNED NULL DEFAULT NULL ,
    `nposts` SMALLINT UNSIGNED NULL DEFAULT NULL ,
    `doc` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `splz` MEDIUMTEXT NULL DEFAULT NULL ) ENGINE = InnoDB;
